# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "5890363ae30a4a3a434fe5df1c4319e3"
application_url = "https://managecustomersubscriptions-muddy-field-2563.fly.dev"
embedded = true
name = "manage_customer_subscriptions"
handle = "manage_customer_subscriptions"

[webhooks]
api_version = "2024-10"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "https://ship-optimal-locale-stylus.trycloudflare.com/webhooks/app/scopes_update"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "https://ship-optimal-locale-stylus.trycloudflare.com/webhooks/app/uninstalled"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_draft_orders,read_orders,read_products,write_customers,write_draft_orders,write_metaobjects,write_orders,write_products"

[auth]
redirect_urls = [
  "https://stuff-although-referrals-successful.trycloudflare.com/auth/callback",
  "https://stuff-although-referrals-successful.trycloudflare.com/auth/shopify/callback",
  "https://stuff-although-referrals-successful.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false

[build]
include_config_on_deploy = true
dev_store_url = "afreshed-dev-store.myshopify.com"
automatically_update_urls_on_dev = true
